import {useState} from "react";
import {NavLink,Outlet,useLocation} from "react-router-dom";
import {FiAlertTriangle,FiBarChart2,FiBookOpen,FiBriefcase,FiCalendar,FiCheckCircle,FiDollarSign,FiFileText,FiGitBranch,FiGrid,FiLayers,FiMap,FiMenu,FiSearch,FiShield,FiSliders,FiTarget,FiX,FiSun,FiMoon} from "react-icons/fi";
const groups=[
["Research",[[ "/","Dashboard",FiGrid],["/scholarships","Scholarship Explorer",FiSearch],["/programs","Master's Programs",FiBookOpen],["/top-10","Top 10 Opportunities",FiTarget],["/comparison","Funding Comparison",FiGitCompare]]],
["Funding",[[ "/funding/need-based","Need-Based Funding",FiShield],["/funding/fully-funded","Fully Funded",FiCheckCircle],["/funding/tuition-free","Tuition-Free Options",FiLayers],["/funding/low-cost","Low-Cost Backups",FiDollarSign],["/deadlines","Deadline Calendar",FiCalendar]]],
["Explore",[[ "/countries","Country Explorer",FiMap],["/regions","Region Explorer",FiLayers],["/fields","Program / Field Explorer",FiBriefcase]]],
["Planning",[[ "/eligibility","Eligibility Checker",FiSliders],["/budget","Budget Calculator",FiBarChart2],["/documents","Document Checklist",FiFileText],["/roadmap","Application Roadmap",FiCalendar],["/do-not-waste-time","Do Not Waste Time On",FiAlertTriangle]]]
];
export default function Layout(){const[open,setOpen]=useState(false);const[dark,setDark]=useState(document.documentElement.classList.contains("dark"));const loc=useLocation();const toggle=()=>{document.documentElement.classList.toggle("dark");setDark(!dark)};return <div className="min-h-screen bg-slate-50 text-slate-900 dark:bg-slate-950 dark:text-white"><div className="mx-auto flex min-h-screen max-w-[1680px]"><aside className={"fixed inset-y-0 left-0 z-40 w-72 overflow-y-auto border-r border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-950 lg:static lg:block "+(open?"block":"hidden lg:block")}><div className="flex items-center justify-between"><div><div className="eyebrow">MSMG Research</div><div className="mt-1 text-lg font-black">Scholarship Intelligence</div></div><button className="icon-btn lg:hidden" onClick={()=>setOpen(false)}><FiX/></button></div><div className="mt-7 space-y-6">{groups.map(([g,links])=><div key={g}><div className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.22em] text-slate-400">{g}</div><nav className="space-y-1">{links.map(([to,label,Icon])=><NavLink end={to==="/"} key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>"flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-semibold "+(isActive?"bg-slate-900 text-white dark:bg-white dark:text-slate-900":"text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800")}><Icon size={16}/>{label}</NavLink>)}</nav></div>)}</div><div className="mt-8 rounded-2xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 dark:border-slate-800 dark:bg-slate-900"><b>Verified on 25 Sep 2026</b><p className="mt-1 text-slate-500">Official facts and ESTIMATE figures are separated. No claim of literal internet exhaustiveness.</p></div></aside><main className="min-w-0 flex-1"><header className="sticky top-0 z-30 border-b border-slate-200 bg-slate-50/90 px-4 py-3 backdrop-blur dark:border-slate-800 dark:bg-slate-950/90 sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4"><button className="icon-btn lg:hidden" onClick={()=>setOpen(true)}><FiMenu/></button><div className="min-w-0"><p className="text-xs text-slate-400">Pakistan-specific master's research</p><p className="truncate text-sm font-bold">{loc.pathname==="/"?"Overview":"Research workspace"}</p></div><button className="icon-btn" onClick={toggle} title="Toggle light and dark mode">{dark?<FiSun/>:<FiMoon/>}</button></div></header><div className="p-4 sm:p-6 lg:p-8"><Outlet/></div></main></div></div>}